version: '2.3'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    runtime: nvidia
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
    - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=neuro
      - POSTGRES_PASSWORD=neuro
      - POSTGRES_DB=neuro_dev

volumes:
  postgres_data: